"""auto vote

Revision ID: 5715c4658046
Revises: 3633025cea9d
Create Date: 2023-01-08 23:42:28.886948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5715c4658046'
down_revision = '3633025cea9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
